# Generated by Django 3.1 on 2021-10-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('views', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество показов')),
                ('clicks', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество кликов')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость кликов')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
            },
        ),
    ]
